### ISSUE TITLE
CHIMES_MODULES should not be specified here, need to specify LMP_MODULES, and shouldn't have MKL

### ISSUE THREAD

**Issue by RKLindsey** [LindseyLab-umich/al_driver-LLfork#35]
https://github.com/LindseyLab-umich/al_driver-LLfork/blob/3d9e675840053dc9d4f5149b5ce8b76683a29fef/examples/simple_iter_single_statepoint-lmp-test/config.py#L66

**Comment by Awwal41** [comment]
Issue has been resolved in pull request #39
