### ISSUE TITLE
Incorrect usage of shutil in develop gen_ff.py

### ISSUE THREAD

**Issue by RKLindsey** [LindseyLab-umich/al_driver-LLfork#38]
@Awwal41 please replace all usages of ``shutil`` with a ``helpers.run_bash_cmd`` call and remove import of shutil.

See, e.g.,: 

- https://github.com/LindseyLab-umich/al_driver-LLfork/blob/d3a3b9fc87400c8ec3dd58f18a55ee2113b7b27d/src/gen_ff.py#L15
- https://github.com/LindseyLab-umich/al_driver-LLfork/blob/d3a3b9fc87400c8ec3dd58f18a55ee2113b7b27d/src/gen_ff.py#L1054

For an example of how to use ``helpers.run_bash_cmd``, see, e.g.: 

- https://github.com/LindseyLab-umich/al_driver-LLfork/blob/d3a3b9fc87400c8ec3dd58f18a55ee2113b7b27d/src/gen_ff.py#L1086

**Comment by Awwal41** [comment]
The issue has been fixed and tested. I have made a pull request.
