### ISSUE TITLE
Missing "sort id" in "dump_modify"

### ISSUE THREAD

**Issue by RKLindsey** [LindseyLab-umich/al_driver-LLfork#42]
@Awwal41 

https://github.com/LindseyLab-umich/al_driver-LLfork/blob/87296a4706a93fe14d7e311c51be4f9b37549593/examples/simple_iter_single_statepoint-lmp-test/ALL_BASE_FILES/LMPMD_BASEFILES/case-0.indep-0.in.lammps#L59

Without "sort id", atom type index gets jumbled. This will cause issues when performing analysis that depends on knowing time-resolved atom positions (e.g., diffusion coefficient or power spectrum).

**Comment by RKLindsey** [comment]
Reminding @S-A-Almohri  :)

**Comment by Awwal41** [comment]
This is already fixed in pull request #38
